const PROJECTS = [
  {
    name: "EthHub",
    description: "A TRUSTED SOURCE IN A TRUSTLESS WORLD",
    image: "ethhub",
    category: "Education",
    address: "0xA19FCDaD77C1F0fd184689aca88BabCF68010347",
    twitter: "@ethhub_io",
    URL: "https://ethhub.io/",
  },
  {
    name: "One Click Dapp",
    description: "Turning smart contracts into easy-to-use dApps",
    image: "ocd",
    category: "Tooling",
    address: "0x9492510BbCB93B6992d8b7Bb67888558E12DCac4",
    twitter: "@pi0neerpat",
    URL: "https://oneclickdapp.com",
  },
  {
    name: "rDAO",
    description: "Programmable interest payments for everyone",
    image: "rdai",
    category: "DeFi",
    address: "0x5D7D257d97D8a81F51187a77C6dD226Fb8424d90",
    twitter: "@rDAI_DAO",
    URL: "https://rdai.money",
  },
  {
    name: "The Altar of rDAI",
    description: "Making rDAI offerings to open source projects",
    image: "altar",
    category: "DeFi",
    address: "0x607EBb69D568DBe1d2283668120036A892E88e89",
    twitter: "@AltarOfrDAI",
    URL: "https://altarofrdai.io/",
  },
  {
    name: "E.TH. Phone Home",
    description: "Voice-calling Ethereum addresses",
    image: "voip",
    category: "Wizardry",
    address: "0x9410A73737E73E105c7CBD57bA64a3073E6A0924",
    twitter: "@ejwessel",
    URL: "https://devpost.com/software/",
  },
  {
    name: "threadpool",
    description: "Engineering + Entrepreneurship",
    image: "thread",
    category: "Education",
    address: "0x18D80Ffdbd08F70B314f06Ae9D1b309135Af9405",
    twitter: "@threadpool_io",
    URL: "https://devpost.com/software/threadpool",
  },

  {
    name: "FLiFF",
    description: "The better way to settle up with your friends",
    image: "fliff",
    category: "DeFi",
    address: "0xaFAEfc6dd3C9feF66f92BA838b132644451F0715",
    twitter: "@AppFliff",
    URL: "https://fliff.app/",
  },
  {
    name: "Cypherplugs",
    description: "Freedom-enhancing Linux distro for cyber protocols",
    image: "cypher",
    category: "Tooling",
    address: "0x65d676F3Eca501b324A636933Cd3b8c4fB5D9228",
    twitter: "@cypherplugs",
    URL: "https://cypherplugs.com",
  },
  {
    name: "Cryptobrawl",
    description: "Interoperable NFT battleground",
    image: "brawl",
    category: "Gaming",
    address: "0x59B96e98B97f3d1A7e59dF53cb0f05E650c4FFfA",
    twitter: "@cryptobrawl",
    URL: "https://cryptobrawl.online",
  },
  {
    name: "Blocks of Notes",
    description: "Anonymous suggestion/complaint box with timed release",
    image: "blocks",
    category: "dApp",
    address: "0x74B0A71a430de8022622c8dDFFe3f9EED0876207",
    twitter: "@CuteManhole",
    URL: "https://devpost.com/software/blocksofnotes",
  },
  {
    name: "BountyUp",
    description: "Bounties platform sustained by rDAI",
    image: "bounty",
    category: "Bounties",
    address: "0x4a7D077E676C4BF3182ce6dcc09afD3217D88bcD",
    twitter: "@cedriking",
    URL: "https://devpost.com/software/bountyup",
  },
  {
    name: "Block Talk",
    description: "E2E encrypted messaging with IPFS storage",
    image: "blocktalk",
    category: "Privacy",
    address: "0x8a68Df0029c9e8B64aD08f9a19a2f8513a4ca70b",
    twitter: "@",
    URL: "https://devpost.com/software/********",
  },
]

export default PROJECTS
